"use client";
import { useEffect, useRef, useState } from "react";
import { pushVault } from "@/lib/sync";
import { HtmlFrame, Icon, Marble, Mark, menuField, NAV_HREF, navIcons, PROVIDERS, ls, tools, suggestions } from "./chrome";
import type { Msg, SavedChat } from "./chrome";
import "./chat-a.css";
import "./chat-b.css";
import "./chat-c.css";

export default function ChatPage() {
  const [ready, setReady] = useState(false);
  const [session, setSession] = useState("");
  const [email, setEmail] = useState("");
  const [activeTool, setActiveTool] = useState("Chat");
  const [contextOpen, setContextOpen] = useState(true);
  const [modelOpen, setModelOpen] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [activeNav, setActiveNav] = useState("Chats");
  const [messages, setMessages] = useState<Msg[]>([]);
  const [sending, setSending] = useState(false);
  const [status, setStatus] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);
  const [attach, setAttach] = useState<{ name: string; text: string } | null>(null);
  const [recent, setRecent] = useState<SavedChat[]>([]);
  const [chatId, setChatId] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const stageRef = useRef<HTMLDivElement>(null);
  const [model, setModel] = useState("");
  const [prov, setProv] = useState("custom");
  const [fBase, setFBase] = useState("");
  const [fKey, setFKey] = useState("");
  const [fModel, setFModel] = useState("");
  const modelWrapRef = useRef<HTMLDivElement>(null);
